tunnel: 9f799748-02f4-4967-a664-7142ebb929ba   # 你的 tunnel UUID
credentials-file: C:\Users\92892\.cloudflared\9f799748-02f4-4967-a664-7142ebb929ba.json

ingress:
  # 规则从上到下匹配，第一个命中的生效
  - hostname: jdbendi.com
    service: http://localhost:5002


  # 最后必须有一条 catchall，否则报错
  - service: http_status:404